from pymongo import MongoClient

client = MongoClient('mongodb://test:test@3.35.251.121', 27017)
# client = MongoClient("localhost", 27017)
db = client.dbproject

data = [
    {
        "menu": "오돌뼈주먹밥 닭알찜",
        "price": 23000,
        "img": "https://imgur.com/JsHEmWt.jpg",
        "tab": 1,
    },
    {
        "menu": "오돌뼈주먹밥 황도",
        "price": 23000,
        "img": "https://imgur.com/cjYKxQK.jpg",
        "tab": 1,
    },
    {
        "menu": "추천 후라이드치킨",
        "price": 18000,
        "img": "https://imgur.com/dl7YBtP.jpg",
        "tab": 1,
    },
    {
        "menu": "추천 무뼈닭발",
        "price": 16000,
        "img": "https://imgur.com/FDhetqd.jpg",
        "tab": 1,
    },
    {
        "menu": "추천 황포족발",
        "price": 18000,
        "img": "https://imgur.com/BCxQHY8.jpg",
        "tab": 1,
    },
    {
        "menu": "추천 김치전",
        "price": 16000,
        "img": "https://imgur.com/ambthFA.jpg",
        "tab": 1,
    },
    {
        "menu": "추천 파전",
        "price": 16000,
        "img": "https://imgur.com/4VMgIM0.jpg",
        "tab": 1,
    },
    {
        "menu": "추천 얼큰수제비탕",
        "price": 18000,
        "img": "https://imgur.com/tueNtKk.jpg",
        "tab": 1,
    },
    {
        "menu": "추천 떡만순튀",
        "price": 15000,
        "img": "https://imgur.com/L4WTxFV.jpg",
        "tab": 1,
    },
    {
        "menu": "얼큰수제비탕",
        "price": 18000,
        "img": "https://imgur.com/tueNtKk.jpg",
        "tab": 2,
    },
    {
        "menu": "만두전골",
        "price": 18000,
        "img": "https://imgur.com/gqSquVV.jpg",
        "tab": 2,
    },
    {
        "menu": "닭볶음탕",
        "price": 22000,
        "img": "https://imgur.com/IF1pB2o.jpg",
        "tab": 2,
    },
    {
        "menu": "찜닭",
        "price": 22000,
        "img": "https://imgur.com/eDlRc5m.jpg",
        "tab": 2,
    },
    {
        "menu": "오뎅탕",
        "price": 17000,
        "img": "https://imgur.com/13ye90m.jpg",
        "tab": 2,
    },
    {
        "menu": "부대찌개",
        "price": 18000,
        "img": "https://imgur.com/zoYUUnk.jpg",
        "tab": 2,
    },
    {
        "menu": "김치찌개",
        "price": 18000,
        "img": "https://imgur.com/tgeqLgo.jpg",
        "tab": 2,
    },
    {
        "menu": "고추장찌개",
        "price": 18000,
        "img": "https://imgur.com/QHHODqM.jpg",
        "tab": 2,
    },
    {
        "menu": "후라이드치킨",
        "price": 18000,
        "img": "https://imgur.com/dl7YBtP.jpg",
        "tab": 3,
    },
    {
        "menu": "양념치킨",
        "price": 19000,
        "img": "https://imgur.com/v25gEUU.jpg",
        "tab": 3,
    },
    {
        "menu": "파닭",
        "price": 19000,
        "img": "https://imgur.com/d31OVP5.jpg",
        "tab": 3,
    },
    {
        "menu": "검은깨 순살",
        "price": 18000,
        "img": "https://imgur.com/CHKzFFH.jpg",
        "tab": 3,
    },
    {
        "menu": "비듬감자",
        "price": 14000,
        "img": "https://imgur.com/pmwm1C5.jpg",
        "tab": 3,
    },
    {
        "menu": "모듬튀김",
        "price": 18000,
        "img": "https://imgur.com/LLiTfGQ.jpg",
        "tab": 3,
    },
    {
        "menu": "치즈쭈꾸미",
        "price": 19000,
        "img": "https://imgur.com/2cXgBwZ.jpg",
        "tab": 4,
    },
    {
        "menu": "치즈소세지",
        "price": 16000,
        "img": "https://imgur.com/K0ScHwo.jpg",
        "tab": 4,
    },
    {
        "menu": "제육볶음주먹밥",
        "price": 18000,
        "img": "https://imgur.com/uS5U2yv.jpg",
        "tab": 4,
    },
    {
        "menu": "무뼈닭발",
        "price": 16000,
        "img": "https://imgur.com/kdB7PiH.jpg",
        "tab": 4,
    },
    {
        "menu": "철판치즈불닭",
        "price": 18000,
        "img": "https://imgur.com/eehfYwo.jpg",
        "tab": 4,
    },
    {
        "menu": "껍데기볶음",
        "price": 16000,
        "img": "https://imgur.com/w6nWaJZ.jpg",
        "tab": 4,
    },
    {
        "menu": "통마늘모래집",
        "price": 16000,
        "img": "https://imgur.com/PM2kuQe.jpg",
        "tab": 4,
    },
    {
        "menu": "두부김치",
        "price": 16000,
        "img": "https://imgur.com/UJQ77Gt.jpg",
        "tab": 4,
    },
    {
        "menu": "매콤골뱅이",
        "price": 18000,
        "img": "https://imgur.com/bDq3hCf.jpg",
        "tab": 4,
    },
    {
        "menu": "파전",
        "price": 16000,
        "img": "https://imgur.com/4VMgIM0.jpg",
        "tab": 4,
    },
    {
        "menu": "김치전",
        "price": 16000,
        "img": "https://imgur.com/ambthFA.jpg",
        "tab": 4,
    },
    {
        "menu": "닭알말이",
        "price": 14000,
        "img": "https://imgur.com/biKkcD8.jpg",
        "tab": 4,
    },
    {
        "menu": "오리훈제",
        "price": 19000,
        "img": "https://imgur.com/EexTAAI.jpg",
        "tab": 5,
    },
    {
        "menu": "황포족발",
        "price": 18000,
        "img": "https://imgur.com/BCxQHY8.jpg",
        "tab": 5,
    },
    {
        "menu": "도토리묵",
        "price": 16000,
        "img": "https://imgur.com/sA3l4YP.jpg",
        "tab": 5,
    },
    {
        "menu": "콘치즈",
        "price": 5000,
        "img": "https://imgur.com/vzPQ9Ha.jpg",
        "tab": 6,
    },
    {
        "menu": "닭알찜",
        "price": 8000,
        "img": "https://imgur.com/SSyVI8N.jpg",
        "tab": 6,
    },
    {
        "menu": "황도",
        "price": 8000,
        "img": "https://imgur.com/WmClsDD.jpg",
        "tab": 6,
    },
    {
        "menu": "김치국밥",
        "price": 6000,
        "img": "https://imgur.com/GNFFp0G.jpg",
        "tab": 6,
    },
    {
        "menu": "신라면 x2",
        "price": 6000,
        "img": "https://imgur.com/X8KCcPi.jpg",
        "tab": 6,
    },
    {
        "menu": "사리곰탕면 x2",
        "price": 6000,
        "img": "https://imgur.com/aMiGQbK.jpg",
        "tab": 6,
    },
    {
        "menu": "짜파게티 x2",
        "price": 6000,
        "img": "https://imgur.com/n6wOnOg.jpg",
        "tab": 6,
    },
    {
        "menu": "양철비빔밥",
        "price": 6000,
        "img": "https://imgur.com/muux0TS.jpg",
        "tab": 6,
    },
    {
        "menu": "황포set1 오돌뼈주먹밥 x 오뎅탕 x 닭알찜",
        "price": 38000,
        "tab": 7,
    },
    {
        "menu": "황포set2 오돌뼈주먹밥 x 오뎅탕 x 황도",
        "price": 38000,
        "tab": 7,
    },
    {
        "menu": "용반장set 매콤골뱅이 x 후라이드치킨",
        "price": 33000,
        "tab": 7,
    },
    {
        "menu": "정반장set 치즈불닭 x 비듬감자 x 쥐포2마리",
        "price": 33000,
        "tab": 7,
    },
    {
        "menu": "백반장set 무뼈닭발 x 닭알찜 x 김가루주먹밥",
        "price": 25000,
        "tab": 7,
    },
    {
        "menu": "공기밥",
        "price": 1000,
        "tab": 8,
    },
    {
        "menu": "우동사리",
        "price": 2000,
        "tab": 8,
    },
    {
        "menu": "라면사리",
        "price": 2000,
        "tab": 8,
    },
    {
        "menu": "도시락",
        "price": 2500,
        "tab": 8,
    },
    {
        "menu": "두부사리",
        "price": 2000,
        "tab": 8,
    },
    {
        "menu": "치즈사리",
        "price": 3000,
        "tab": 8,
    },
    {
        "menu": "주먹밥",
        "price": 3000,
        "tab": 8,
    },
    {
        "menu": "소면사리",
        "price": 2000,
        "tab": 8,
    },
    {
        "menu": "수제비사리",
        "price": 3000,
        "tab": 8,
    },
    {
        "menu": "김치참치주먹밥",
        "price": 5000,
        "tab": 8,
    },
    {
        "menu": "처음처럼",
        "price": 4500,
        "img": "https://imgur.com/4imAg3a.jpg",
        "tab": 9,
    },
    {
        "menu": "대장부",
        "price": 4500,
        "img": "https://imgur.com/km2rweM.jpg",
        "tab": 9,
    },
    {
        "menu": "참이슬 클래식",
        "price": 4500,
        "img": "https://imgur.com/4ihuPoT.jpg",
        "tab": 9,
    },
    {
        "menu": "참이슬 후레쉬",
        "price": 4500,
        "img": "https://imgur.com/GE9S3m3.jpg",
        "tab": 9,
    },
    {
        "menu": "진로이즈백",
        "price": 4500,
        "img": "https://imgur.com/7NqroZ1.jpg",
        "tab": 9,
    },
    {
        "menu": "부산 좋은데이",
        "price": 5000,
        "img": "https://imgur.com/hjOYCyw.jpg",
        "tab": 9,
    },
    {
        "menu": "부산 대선",
        "price": 5000,
        "img": "https://imgur.com/fsdYHxc.jpg",
        "tab": 9,
    },
    {
        "menu": "경남 화이트",
        "price": 5000,
        "img": "https://imgur.com/yxsc5AN.jpg",
        "tab": 9,
    },
    {
        "menu": "경북 참소주",
        "price": 5000,
        "img": "https://imgur.com/L5ux3fP.jpg",
        "tab": 9,
    },
    {
        "menu": "제주 한라산",
        "price": 5000,
        "img": "https://imgur.com/xToSzjr.jpg",
        "tab": 9,
    },
    {
        "menu": "제주 푸른밤",
        "price": 5000,
        "img": "https://imgur.com/gwsy4en.jpg",
        "tab": 9,
    },
    {
        "menu": "전남 잎새주",
        "price": 5000,
        "img": "https://imgur.com/er9yx2E.jpg",
        "tab": 9,
    },
    {
        "menu": "충남 O2린",
        "price": 5000,
        "img": "https://imgur.com/pSfqmMK.jpg",
        "tab": 9,
    },
    {
        "menu": "참이슬 자몽",
        "price": 4500,
        "img": "https://imgur.com/sqU2CwG.jpg",
        "tab": 9,
    },
    {
        "menu": "참이슬 청포도",
        "price": 4500,
        "img": "https://imgur.com/pFogMIW.jpg",
        "tab": 9,
    },
    {
        "menu": "참이슬 자두",
        "price": 4500,
        "img": "https://imgur.com/Dvwvx4T.jpg",
        "tab": 9,
    },
    {
        "menu": "순하리 사과",
        "price": 4500,
        "img": "https://imgur.com/gPgxS4e.jpg",
        "tab": 9,
    },
    {
        "menu": "좋은데이 꽐라만시",
        "price": 4500,
        "img": "https://imgur.com/YLF1GrE.jpg",
        "tab": 9,
    },
    {
        "menu": "트로피칼 톡소다",
        "price": 4500,
        "img": "https://imgur.com/jEiP2N6.jpg",
        "tab": 9,
    },
    {
        "menu": "설중매 스파클링",
        "price": 5000,
        "img": "https://imgur.com/p7U6Z7k.jpg",
        "tab": 9,
    },
    {
        "menu": "청하",
        "price": 5000,
        "img": "https://imgur.com/sgiRe3t.jpg",
        "tab": 10,
    },
    {
        "menu": "매화수",
        "price": 5000,
        "img": "https://imgur.com/i0fIX8S.jpg",
        "tab": 10,
    },
    {
        "menu": "生클라우드 병",
        "price": 4500,
        "img": "https://imgur.com/7S24BTD.jpg",
        "tab": 10,
    },
    {
        "menu": "피츠 병",
        "price": 4500,
        "img": "https://imgur.com/I7Ish9j.jpg",
        "tab": 10,
    },
    {
        "menu": "테라 병",
        "price": 4500,
        "img": "https://imgur.com/butUagl.jpg",
        "tab": 10,
    },
    {
        "menu": "하이트 병",
        "price": 4500,
        "img": "https://imgur.com/rXZMLUy.jpg",
        "tab": 10,
    },
    {
        "menu": "生클라우드 475cc",
        "price": 4000,
        "img": "https://imgur.com/ZWHMkCk.jpg",
        "tab": 10,
    },
    {
        "menu": "生클라우드 1700cc",
        "price": 15000,
        "img": "https://imgur.com/rQ9DP8i.jpg",
        "tab": 10,
    },
    {
        "menu": "장수막걸리",
        "price": 4000,
        "img": "https://imgur.com/nFfD87u.jpg",
        "tab": 10,
    },
    {
        "menu": "알밤막걸리",
        "price": 4000,
        "img": "https://imgur.com/K9jg8DP.jpg",
        "tab": 10,
    },
    {
        "menu": "펩시",
        "price": 2000,
        "img": "https://imgur.com/FQdk7Io.jpg",
        "tab": 11,
    },
    {
        "menu": "사이다",
        "price": 2000,
        "img": "https://imgur.com/NoXCVE1.jpg",
        "tab": 11,
    },
    {
        "menu": "미린다 오렌지",
        "price": 2000,
        "img": "https://imgur.com/JG0b4bZ.jpg",
        "tab": 11,
    },
    {
        "menu": "미린다 파인애플",
        "price": 2000,
        "img": "https://imgur.com/q9gqeLO.jpg",
        "tab": 11,
    },
    {
        "menu": "토닉워터",
        "price": 2000,
        "img": "https://imgur.com/Q9OpL5y.jpg",
        "tab": 11,
    },
]

db.hwangpo.delete_many({})
db.hwangpo.insert_many(data)

exit(1)