from pymongo import MongoClient

client = MongoClient('mongodb://test:test@3.35.251.121', 27017)
# client = MongoClient("localhost", 27017)
db = client.dbproject

data = [
    {
        "menu": "꽃게라면",
        "price": 5000,
        "img": "https://imgur.com/AlffkFw.jpg",
        "tab": 1,
    },
    {
        "menu": "옛날 도시락",
        "price": 5000,
        "img": "https://imgur.com/mweGzCI.jpg",
        "tab": 1,
    },
    {
        "menu": "계란찜",
        "price": 7000,
        "img": "https://imgur.com/X2Vj7s7.jpg",
        "tab": 1,
    },
    {
        "menu": "스팸 계란 후라이",
        "price": 7000,
        "img": "https://imgur.com/bT2qWzM.jpg",
        "tab": 1,
    },
    {
        "menu": "아이스 황도",
        "price": 7000,
        "img": "https://imgur.com/rxkpS7b.jpg",
        "tab": 1,
    },
    {
        "menu": "간장계란밥",
        "price": 7000,
        "img": "https://imgur.com/ytNXeVE.jpg",
        "tab": 1,
    },
    {
        "menu": "오다리튀김",
        "price": 7000,
        "img": "https://imgur.com/lEqksAK.jpg",
        "tab": 1,
    },
    {
        "menu": "콘치즈",
        "price": 7000,
        "img": "https://imgur.com/jFlKbj7.jpg",
        "tab": 1,
    },
    {
        "menu": "스팸 김치덮밥",
        "price": 7000,
        "img": "https://imgur.com/leBU7ZN.jpg",
        "tab": 1,
    },
    {
        "menu": "김치볶음밥",
        "price": 7000,
        "img": "https://imgur.com/gmDUPDK.jpg",
        "tab": 1,
    },
    {
        "menu": "모듬감자",
        "price": 7000,
        "img": "https://imgur.com/G5dmGyh.jpg",
        "tab": 1,
    },
    {
        "menu": "닭껍질 튀김",
        "price": 9000,
        "img": "https://imgur.com/rfgiHyM.jpg",
        "tab": 2,
    },
    {
        "menu": "통마늘 똥집",
        "price": 9000,
        "img": "https://imgur.com/J8kx2E2.jpg",
        "tab": 2,
    },
    {
        "menu": "케이준 샐러드",
        "price": 9000,
        "img": "https://imgur.com/xbhMY3I.jpg",
        "tab": 2,
    },
    {
        "menu": "소고기 짜파구리",
        "price": 9000,
        "img": "https://imgur.com/qPmPNgg.jpg",
        "tab": 2,
    },
    {
        "menu": "Talk 계란탕",
        "price": 9000,
        "img": "https://imgur.com/XgfN7D5.jpg",
        "tab": 2,
    },
    {
        "menu": "토마토 카나페 플래터",
        "price": 9000,
        "img": "https://imgur.com/W0N7pJR.jpg",
        "tab": 2,
    },
    {
        "menu": "떡만두 전골",
        "price": 9000,
        "img": "https://imgur.com/kCiaVNI.jpg",
        "tab": 2,
    },
    {
        "menu": "오징어 숙회",
        "price": 9000,
        "img": "https://imgur.com/BvEZRQY.jpg",
        "tab": 2,
    },
    {
        "menu": "불난 짬뽕탕",
        "price": 12000,
        "img": "https://imgur.com/60bMcUx.jpg",
        "tab": 3,
    },
    {
        "menu": "우삼겹 숙주볶음",
        "price": 12000,
        "img": "https://imgur.com/tQ779BV.jpg",
        "tab": 3,
    },
    {
        "menu": "크리스피 반통닭",
        "price": 12000,
        "img": "https://imgur.com/0NCqXMe.jpg",
        "tab": 3,
    },
    {
        "menu": "버팔로윙봉",
        "price": 12000,
        "img": "https://imgur.com/x6T5ZkP.jpg",
        "tab": 3,
    },
    {
        "menu": "떠먹는피자",
        "price": 12000,
        "img": "https://imgur.com/35ys5vb.jpg",
        "tab": 3,
    },
    {
        "menu": "데리야끼 순살치킨",
        "price": 12000,
        "img": "https://imgur.com/aWUYx4N.jpg",
        "tab": 3,
    },
    {
        "menu": "칠리 순살치킨",
        "price": 12000,
        "img": "https://imgur.com/8s1pPDB.jpg",
        "tab": 3,
    },
{
        "menu": "화채",
        "price": 12000,
        "img": "https://imgur.com/mrSQzeL.jpg",
        "tab": 3,
    },
    {
        "menu": "해물로제 당면 파스타",
        "price": 12000,
        "img": "https://imgur.com/RvFNEGO.jpg",
        "tab":3,
    },
{
        "menu": "짜장 대패삼겹",
        "price": 12000,
        "img": "https://imgur.com/oU2z5rF.jpg",
        "tab": 3,
    },
    {
        "menu": "칠리 치즈포테이토",
        "price": 12000,
        "img": "https://imgur.com/CC3qwH1.jpg",
        "tab": 3,
    },
{
        "menu": "치즈불닭",
        "price": 12000,
        "img": "https://imgur.com/O6OLdG1.jpg",
        "tab": 3,
    },
    {
        "menu": "칠리 깐쇼 새우",
        "price": 12000,
        "img": "https://imgur.com/mj0oIoa.jpg",
        "tab": 3,
    },
{
        "menu": "오돌뼈 주먹밥",
        "price": 12000,
        "img": "https://imgur.com/VLGvX8a.jpg",
        "tab": 3,
    },
    {
        "menu": "치즈계란말이",
        "price": 12000,
        "img": "https://imgur.com/4eVpGRc.jpg",
        "tab": 3,
    },
{
        "menu": "한치",
        "price": 12000,
        "img": "https://imgur.com/5ULrtCg.jpg",
        "tab": 3,
    },
    {
        "menu": "반건조 오징어",
        "price": 12000,
        "img": "https://imgur.com/eE7ljoC.jpg",
        "tab": 3,
    },
{
        "menu": "소불고기 전골",
        "price": 12000,
        "img": "https://imgur.com/EpZQkYU.jpg",
        "tab": 3,
    },
    {
        "menu": "소고기 스테이크 샐러드",
        "price": 12000,
        "img": "https://imgur.com/jgWuujf.jpg",
        "tab": 3,
    },
{
        "menu": "새우 감바스",
        "price": 12000,
        "img": "https://imgur.com/Sc1YWDc.jpg",
        "tab": 3,
    },
    {
        "menu": "Talk 치즈와 비스켓",
        "price": 12000,
        "img": "https://imgur.com/3mZ21eL.jpg",
        "tab": 3,
    },
    {
        "menu": "미니과일",
        "price": 12000,
        "img": "https://imgur.com/7SkstJ4.jpg",
        "tab": 3,
    },
    {
        "menu": "통골뱅이소면",
        "price": 16000,
        "img": "https://imgur.com/2jn3L5J.jpg",
        "tab": 4,
    },
    {
        "menu": "돼지고기 김치찌개",
        "price": 16000,
        "img": "https://imgur.com/7dZYGHc.jpg",
        "tab": 4,
    },
    {
        "menu": "모둠수제꼬치 어묵탕",
        "price": 16000,
        "img": "https://imgur.com/DJFn4gM.jpg",
        "tab": 4,
    },
{
        "menu": "신당동 국물떡볶이",
        "price": 16000,
        "img": "https://imgur.com/O4e9Z5X.jpg",
        "tab": 4,
    },
    {
        "menu": "이태원 부대찌개",
        "price": 16000,
        "img": "https://imgur.com/sDaOXf2.jpg",
        "tab": 4,
    },
    {
        "menu": "통삽겹 김치찜",
        "price": 16000,
        "img": "https://imgur.com/fUBiGDw.jpg",
        "tab": 4,
    },
{
        "menu": "큐브 스테이크",
        "price": 16000,
        "img": "https://imgur.com/l3HYUwI.jpg",
        "tab": 4,
    },
    {
        "menu": "수제소세지",
        "price": 16000,
        "img": "https://imgur.com/2CIundF.jpg",
        "tab": 4,
    },
    {
        "menu": "치즈퐁듀소세지",
        "price": 16000,
        "img": "https://imgur.com/0hx3BMI.jpg",
        "tab": 4,
    },
    {
        "menu": "과일 요거트",
        "price": 16000,
        "img": "https://imgur.com/PyXeU6F.jpg",
        "tab": 4,
    },
    {
        "menu": "계절과일",
        "price": 24000,
        "img": "https://imgur.com/EIJsZfY.jpg",
        "tab": 4,
    },

    {
        "menu": "과일치즈 플래터",
        "price": 28000,
        "img": "https://imgur.com/vemYGzS.jpg",
        "tab": 4,
    },
    {
        "menu": "처음처럼",
        "price": 5000,
        "img": "https://imgur.com/XZAmIxt.jpg",
        "tab": 5,
    },

    {
        "menu": "순하리 처음처럼 사과",
        "price": 5000,
        "img": "https://imgur.com/dHbCaaE.jpg",
        "tab": 5,
    },
    {
        "menu": "진로이즈백",
        "price": 5000,
        "img": "https://imgur.com/mFAp6F5.jpg",
        "tab": 5,
    },
    {
        "menu": "참이슬",
        "price": 5000,
        "img": "https://imgur.com/1R8irpG.jpg",
        "tab": 5,
    },
    {
        "menu": "자두에 이슬",
        "price": 5000,
        "img": "https://imgur.com/6fPCkCd.jpg",
        "tab": 5,
    },
    {
        "menu": "아이셔에 이슬",
        "price": 5000,
        "img": "https://imgur.com/JoqVUur.jpg",
        "tab": 5,
    },

    {
        "menu": "이슬톡톡",
        "price": 6000,
        "img": "https://imgur.com/ynN5oWd.jpg",
        "tab": 5,
    },
    {
        "menu": "청하",
        "price": 6000,
        "img": "https://imgur.com/sThLygi.jpg",
        "tab": 5,
    },
    {
        "menu": "매화수",
        "price": 6000,
        "img": "https://imgur.com/lA3a4ys.jpg",
        "tab": 5,
    },
    {
        "menu": "클라우드 병",
        "price": 6000,
        "img": "https://imgur.com/2Btptge.jpg",
        "tab": 5,
    },
    {
        "menu": "카스 병",
        "price": 6000,
        "img": "https://imgur.com/Bh69ZJi.jpg",
        "tab": 5,
    },
    {
        "menu": "테라 병",
        "price": 6000,
        "img": "https://imgur.com/kt2sib4.jpg",
        "tab": 5,
    },
    {
        "menu": "생맥주 425cc",
        "price": 4000,
        "img": "https://imgur.com/hWKaajo.jpg",
        "tab": 5,
    },
    {
        "menu": "생맥주 1700cc",
        "price": 15000,
        "img": "https://imgur.com/sz0vEym.jpg",
        "tab": 5,
    },
    {
        "menu": "생맥주 2700cc",
        "price": 20000,
        "img": "https://imgur.com/2a8dDtw.jpg",
        "tab": 5,
    },
    {
        "menu": "콜라",
        "price": 3000,
        "img": "https://imgur.com/JhbIb3J.jpg",
        "tab": 5,
    },
    {
        "menu": "사이다",
        "price": 3000,
        "img": "https://imgur.com/ihkwt3w.jpg",
        "tab": 5,
    },
    {
        "menu": "핫식스",
        "price": 3000,
        "img": "https://imgur.com/kOLIbXQ.jpg",
        "tab": 5,
    },
    {
        "menu": "토닉워터",
        "price": 3000,
        "img": "https://imgur.com/ROEriRK.jpg",
        "tab": 5,
    },
    {
        "menu": "초코에몽",
        "price": 2000,
        "img": "https://imgur.com/5KaODbi.jpg",
        "tab": 5,
    },
    {
        "menu": "골든블루450ml",
        "price": 109000,
        "img": "https://imgur.com/isEgdjJ.jpg",
        "tab": 6,
    },
    {
        "menu": "예거마이스터700ml",
        "price": 109000,
        "img": "https://imgur.com/hvQX3xO.jpg",
        "tab": 6,
    },
    {
        "menu": "봄베이사파이어진750ml",
        "price": 109000,
        "img": "https://imgur.com/rCMlA9E.jpg",
        "tab": 6,
    },
    {
        "menu": "잭다니엘700ml",
        "price": 119000,
        "img": "https://imgur.com/8QSDCu1.jpg",
        "tab": 6,
    },
{
        "menu": "잭다니엘허니700ml",
        "price": 119000,
        "img": "https://imgur.com/YLu3MMm.jpg",
        "tab": 6,
    },
    {
        "menu": "아그와700ml",
        "price": 109000,
        "img": "https://imgur.com/LecFqlF.jpg",
        "tab": 6,
    },
    {
        "menu": "X레이티드750ml",
        "price": 119000,
        "img": "https://imgur.com/ikFanc4.jpg",
        "tab": 6,
    },

]

db.talk.delete_many({})
db.talk.insert_many(data)

exit(1)