from pymongo import MongoClient

client = MongoClient('mongodb://test:test@3.35.251.121', 27017)
# client = MongoClient("localhost", 27017)
db = client.dbproject

data = [
    {
        "menu": "스팸 계란 후라이",
        "price": 7000,
        "img": "https://imgur.com/8KDsTIV.jpg",
        "tab": 1,
    },
    {
        "menu": "새우맛 계란찜",
        "price": 7000,
        "img": "https://imgur.com/kDbUzOU.jpg",
        "tab": 1,
    },
    {
        "menu": "아이스황도",
        "price": 7000,
        "img": "https://imgur.com/U9Q5Nyc.jpg",
        "tab": 1,
    },
    {
        "menu": "오다리튀김",
        "price": 7000,
        "img": "https://imgur.com/mz9W8iS.jpg",
        "tab": 1,
    },
    {
        "menu": "콘버터",
        "price": 7000,
        "img": "https://imgur.com/RZYursz.jpg",
        "tab": 1,
    },
    {
        "menu": "아이스링파인",
        "price": 7000,
        "img": "https://imgur.com/5vdcJV2.jpg",
        "tab": 1,
    },
    {
        "menu": "꽃게라면",
        "price": 5000,
        "img": "https://imgur.com/IPLualv.jpg",
        "tab": 1,
    },
    {
        "menu": "간장계란밥",
        "price": 7000,
        "img": "https://imgur.com/odRnZs8.jpg",
        "tab": 1,
    },
    {
        "menu": "스팸김치덮밥",
        "price": 7000,
        "img": "https://imgur.com/lRFDY9u.jpg",
        "tab": 1,
    },
    {
        "menu": "옛날도시락",
        "price": 5000,
        "img": "https://imgur.com/O2h3hAB.jpg",
        "tab": 1,
    },
    {
        "menu": "김치볶음밥",
        "price": 7000,
        "img": "https://imgur.com/6haRmqa.jpg",
        "tab": 1,
    },
    {
        "menu": "짜치계",
        "price": 7000,
        "img": "https://imgur.com/mmCgrOS.jpg",
        "tab": 1,
    },
    {
        "menu": "케이준샐러드",
        "price": 9000,
        "img": "https://imgur.com/ucRgHvZ.jpg",
        "tab": 2,
    },
    {
        "menu": "통오징어숙회",
        "price": 9000,
        "img": "https://imgur.com/dRQa7hr.jpg",
        "tab": 2,
    },
    {
        "menu": "칠리치킨볼",
        "price": 9000,
        "img": "https://imgur.com/15tnBS6.jpg",
        "tab": 2,
    },
    {
        "menu": "통마늘똥집",
        "price": 9000,
        "img": "https://imgur.com/CXq1zA1.jpg",
        "tab": 2,
    },
    {
        "menu": "스파이시 닭껍질튀김",
        "price": 9000,
        "img": "https://imgur.com/R0qkCPk.jpg",
        "tab": 2,
    },
    {
        "menu": "크리스피 닭똥집",
        "price": 9000,
        "img": "https://imgur.com/HgiGuYG.jpg",
        "tab": 2,
    },
    {
        "menu": "모둠감자튀김",
        "price": 9000,
        "img": "https://imgur.com/nLelNS7.jpg",
        "tab": 2,
    },
    {
        "menu": "옛날 반통닭",
        "price": 9000,
        "img": "https://imgur.com/vCLkYUq.jpg",
        "tab": 2,
    },
    {
        "menu": "타코야끼",
        "price": 9000,
        "img": "https://imgur.com/sWW7AwC.jpg",
        "tab": 2,
    },
    {
        "menu": "철판소세지",
        "price": 9000,
        "img": "https://imgur.com/SryTOsV.jpg",
        "tab": 2,
    },
    {
        "menu": "참치김치찌개",
        "price": 9000,
        "img": "https://imgur.com/t9KQ2Ib.jpg",
        "tab": 2,
    },
    {
        "menu": "데리야끼순살치킨",
        "price": 12000,
        "img": "https://imgur.com/2PrxvZh.jpg",
        "tab": 3,
    },
    {
        "menu": "칠리순살치킨",
        "price": 12000,
        "img": "https://imgur.com/xlneXGG.jpg",
        "tab": 3,
    },
    {
        "menu": "두부김치",
        "price": 12000,
        "img": "https://imgur.com/SJGBpWc.jpg",
        "tab": 3,
    },
    {
        "menu": "크림우동",
        "price": 12000,
        "img": "https://imgur.com/QCSXg2W.jpg",
        "tab": 3,
    },
    {
        "menu": "왕새우튀김",
        "price": 12000,
        "img": "https://imgur.com/OGiHKw3.jpg",
        "tab": 3,
    },
    {
        "menu": "화채",
        "price": 12000,
        "img": "https://imgur.com/BLbVdwF.jpg",
        "tab": 3,
    },
    {
        "menu": "북어계란탕",
        "price": 12000,
        "img": "https://imgur.com/oS1c34G.jpg",
        "tab": 3,
    },
    {
        "menu": "얼큰어묵탕",
        "price": 12000,
        "img": "https://imgur.com/kMHhpFL.jpg",
        "tab": 3,
    },
    {
        "menu": "떡만두전골",
        "price": 12000,
        "img": "https://imgur.com/XPi0Bj2.jpg",
        "tab": 3,
    },
    {
        "menu": "백함조개탕",
        "price": 12000,
        "img": "https://imgur.com/bIe3rom.jpg",
        "tab": 3,
    },
    {
        "menu": "국물떡볶이",
        "price": 12000,
        "img": "https://imgur.com/dJd8oxJ.jpg",
        "tab": 3,
    },
    {
        "menu": "버팔로윙봉",
        "price": 12000,
        "img": "https://imgur.com/GRsh54c.jpg",
        "tab": 3,
    },
    {
        "menu": "반건조 노가리",
        "price": 12000,
        "img": "https://imgur.com/xCPoq3O.jpg",
        "tab": 3,
    },
    {
        "menu": "떠먹는 피자",
        "price": 12000,
        "img": "https://imgur.com/hmb8r8T.jpg",
        "tab": 3,
    },
    {
        "menu": "칠리치즈포테이토",
        "price": 12000,
        "img": "https://imgur.com/dxh8KQd.jpg",
        "tab": 3,
    },
    {
        "menu": "칠리깐쇼새우",
        "price": 12000,
        "img": "https://imgur.com/wI4vdWH.jpg",
        "tab": 3,
    },
    {
        "menu": "통오징어주먹밥",
        "price": 12000,
        "img": "https://imgur.com/xxgHSZl.jpg",
        "tab": 3,
    },
    {
        "menu": "치즈불닭",
        "price": 12000,
        "img": "https://imgur.com/YElSbEa.jpg",
        "tab": 3,
    },
    {
        "menu": "반건조 오징어",
        "price": 12000,
        "img": "https://imgur.com/kZmTJAN.jpg",
        "tab": 3,
    },
    {
        "menu": "오돌뼈 주먹밥",
        "price": 12000,
        "img": "https://imgur.com/urocH6z.jpg",
        "tab": 3,
    },
    {
        "menu": "치즈계란말이",
        "price": 12000,
        "img": "https://imgur.com/aPRlnl3.jpg",
        "tab": 3,
    },
    {
        "menu": "한치",
        "price": 12000,
        "img": "https://imgur.com/m0adbZ5.jpg",
        "tab": 3,
    },
    {
        "menu": "미니과일",
        "price": 12000,
        "img": "https://imgur.com/FNRezVy.jpg",
        "tab": 3,
    },
    {
        "menu": "소불고기전골",
        "price": 16000,
        "img": "https://imgur.com/bkmZ8cT.jpg",
        "tab": 4,
    },
    {
        "menu": "부대찌개",
        "price": 16000,
        "img": "https://imgur.com/ELjoXtl.jpg",
        "tab": 4,
    },
    {
        "menu": "통삼겹김치찜",
        "price": 16000,
        "img": "https://imgur.com/pApC568.jpg",
        "tab": 4,
    },
    {
        "menu": "해물짬뽕탕",
        "price": 16000,
        "img": "https://imgur.com/R3O1w8k.jpg",
        "tab": 4,
    },
    {
        "menu": "모듬꼬치수제어묵탕",
        "price": 16000,
        "img": "https://imgur.com/EQCs8y6.jpg",
        "tab": 4,
    },
    {
        "menu": "차돌박이숙주볶음",
        "price": 16000,
        "img": "https://imgur.com/0GGBsF3.jpg",
        "tab": 4,
    },
    {
        "menu": "돼지고기김치찌개",
        "price": 16000,
        "img": "https://imgur.com/WVJ3foD.jpg",
        "tab": 4,
    },
    {
        "menu": "크림짬뽕탕",
        "price": 16000,
        "img": "https://imgur.com/yETDkYJ.jpg",
        "tab": 4,
    },
    {
        "menu": "나가사키짬뽕탕",
        "price": 16000,
        "img": "https://imgur.com/fApQolF.jpg",
        "tab": 4,
    },
    {
        "menu": "크리스피후라이드치킨",
        "price": 16000,
        "img": "https://imgur.com/fibILXy.jpg",
        "tab": 4,
    },
    {
        "menu": "통골뱅이 소면",
        "price": 16000,
        "img": "https://imgur.com/ztGKfZl.jpg",
        "tab": 4,
    },
    {
        "menu": "과일 요거트",
        "price": 16000,
        "img": "https://imgur.com/BWIKchk.jpg",
        "tab": 4,
    },
    {
        "menu": "계절과일",
        "price": 24000,
        "img": "https://imgur.com/ZAjfaZp.jpg",
        "tab": 4,
    },
    {
        "menu": "처음처럼",
        "price": 5000,
        "img": "https://imgur.com/XZAmIxt.jpg",
        "tab": 5,
    },

    {
        "menu": "순하리 처음처럼 사과",
        "price": 5000,
        "img": "https://imgur.com/dHbCaaE.jpg",
        "tab": 5,
    },
    {
        "menu": "진로이즈백",
        "price": 5000,
        "img": "https://imgur.com/mFAp6F5.jpg",
        "tab": 5,
    },
    {
        "menu": "참이슬",
        "price": 5000,
        "img": "https://imgur.com/1R8irpG.jpg",
        "tab": 5,
    },
    {
        "menu": "자두에 이슬",
        "price": 5000,
        "img": "https://imgur.com/6fPCkCd.jpg",
        "tab": 5,
    },
    {
        "menu": "아이셔에 이슬",
        "price": 5000,
        "img": "https://imgur.com/JoqVUur.jpg",
        "tab": 5,
    },
    {
        "menu": "이슬톡톡",
        "price": 6000,
        "img": "https://imgur.com/ynN5oWd.jpg",
        "tab": 5,
    },
    {
        "menu": "청하",
        "price": 6000,
        "img": "https://imgur.com/sThLygi.jpg",
        "tab": 5,
    },
    {
        "menu": "매화수",
        "price": 6000,
        "img": "https://imgur.com/lA3a4ys.jpg",
        "tab": 5,
    },
    {
        "menu": "클라우드 병",
        "price": 6000,
        "img": "https://imgur.com/2Btptge.jpg",
        "tab": 5,
    },
    {
        "menu": "카스 병",
        "price": 6000,
        "img": "https://imgur.com/Bh69ZJi.jpg",
        "tab": 5,
    },
    {
        "menu": "테라 병",
        "price": 6000,
        "img": "https://imgur.com/kt2sib4.jpg",
        "tab": 5,
    },
    {
        "menu": "생맥주 500cc",
        "price": 4500,
        "img": "https://imgur.com/zDINDqu.jpg",
        "tab": 5,
    },
    {
        "menu": "생맥주 1700cc",
        "price": 15000,
        "img": "https://imgur.com/sz0vEym.jpg",
        "tab": 5,
    },
    {
        "menu": "생맥주 2700cc",
        "price": 20000,
        "img": "https://imgur.com/2a8dDtw.jpg",
        "tab": 5,
    },
    {
        "menu": "콜라",
        "price": 3000,
        "img": "https://imgur.com/JhbIb3J.jpg",
        "tab": 5,
    },
    {
        "menu": "사이다",
        "price": 3000,
        "img": "https://imgur.com/ihkwt3w.jpg",
        "tab": 5,
    },
    {
        "menu": "핫식스",
        "price": 3000,
        "img": "https://imgur.com/kOLIbXQ.jpg",
        "tab": 5,
    },
    {
        "menu": "토닉워터",
        "price": 3000,
        "img": "https://imgur.com/ROEriRK.jpg",
        "tab": 5,
    },
    {
        "menu": "초코에몽",
        "price": 2000,
        "img": "https://imgur.com/5KaODbi.jpg",
        "tab": 5,
    },
    {
        "menu": "골든블루450ml",
        "price": 109000,
        "img": "https://imgur.com/isEgdjJ.jpg",
        "tab": 6,
    },
    {
        "menu": "예거마이스터700ml",
        "price": 109000,
        "img": "https://imgur.com/hvQX3xO.jpg",
        "tab": 6,
    },
    {
        "menu": "봄베이사파이어진750ml",
        "price": 109000,
        "img": "https://imgur.com/rCMlA9E.jpg",
        "tab": 6,
    },
    {
        "menu": "잭다니엘700ml",
        "price": 119000,
        "img": "https://imgur.com/8QSDCu1.jpg",
        "tab": 6,
    },
{
        "menu": "잭다니엘허니700ml",
        "price": 119000,
        "img": "https://imgur.com/YLu3MMm.jpg",
        "tab": 6,
    },
    {
        "menu": "아그와700ml",
        "price": 109000,
        "img": "https://imgur.com/LecFqlF.jpg",
        "tab": 6,
    },
    {
        "menu": "X레이티드750ml",
        "price": 119000,
        "img": "https://imgur.com/ikFanc4.jpg",
        "tab": 6,
    },
]

db.masillia.delete_many({})
db.masillia.insert_many(data)

exit(1)